Bakery-EFUB/bakery_front

package-lock.json
package.json
src/components/ButtonSidebar.js
src/components/SearchBar.js
src/components/Sidebar/Sidebar.css
src/components/Sidebar/SidebarData.js
src/components/TopBar.js
src/images/Profile.svg
src/images/SidebarCloseBtn.svg

resolve #23
사이드바 작업입니다
https://user-images.githubusercontent.com/79822913/178171345-5a5fc24b-d627-4263-ab1c-688707a29b19.mp4

feat:사이드바 추가

---

src/pages/PreviewModal.js

resolve #27 
미리보기 모달창 작업 했습니다.
https://user-images.githubusercontent.com/60884877/178285094-3833c3f0-519b-48c9-9288-862b1c6977ff.mov
모달창 열려있을 때 뒤 페이지 클릭 안되도록 background 요소까지 추가해서 작업했습니다.

feat: 미리 보기 모달창

---

src/App.js
src/components/TopBar.js
src/pages/Proposal7.js
src/styles/calendar.css

resolve #{없음}
모든 기종에서 호환되도록 컴포넌트 크기 수정했습니다. 
생략
생략

fix : css width 값 단위 수정

---

src/pages/ShopMyPageStart.js

feat: 마이페이지 로고 생성

---

src/components/FileUpload.js
src/pages/ShopInformationRegister.js

resolve #{67}
파일 업로드 컴포넌트 완성
component > FileUpload.js 에 피그마기준 제안서6페이지에 들어가는 파일 업로드 로직 짜두었습니다.

feat: 파일업로드 컴포넌트 완성

---

src/pages/ShopMyPageProgressive.js

feat:마진으로 ui수정, 라우터 연결

---

src/common/http.js
src/components/Fileupload/ShopImgUpload.js
src/components/Fileupload/ShopMenuUpload.js
src/pages/Auth/LoginLoading.js
src/pages/MyPage/ShopInformationRegister.js

feat:이미지 삭제 컴포넌트 구현

---

package-lock.json
package.json
src/pages/OurService.js

feat: UI 수정

---

src/App.js
src/api/store.js
src/components/HomeCardDisplay/OrderDisplay.js
src/components/HomeCardDisplay/ShopDisplay.js
src/components/WholeProposals/ChooseBox.js
src/pages/AccountSetting.js
src/pages/AllProposal.js
src/pages/Auth/LoginHome.js
src/pages/OurService.js
src/pages/ShopSearch/Recommend.js

feat: 백엔드 연동

---

src/pages/MyPage/ShopMemberMyPage.js

feat : 내 제안서 보기

---

src/components/WholeProposals/ChooseBox.js
src/components/WholeProposals/PropasalBox.js
src/pages/SeeProposal/AllProposal.js

다중필터 제외 구현 완료

---

src/components/Common/Sidebar/TopBar.js
src/pages/ServiceInfo/OurService.js

/about 페이지 ui 수정

---

package-lock.json
package.json
src/components/WholeProposals/ChooseBox.js
src/components/WholeProposals/PropasalBox.js
src/pages/AccountSetting/AccountSetting.js
src/pages/SeeProposal/AllProposal.js

다중선택 api 연동 말고 구현 완료

---

src/components/Common/Sidebar/TopBar.js
src/pages/MyPage/ClientMypage.js

ui 오류 수정(마이페이지 & 메뉴바)

---

src/components/WholeProposals/ChooseBox.js
src/pages/SeeProposal/AllProposal.js

제안서 필터링 작업 했습니다.
api가 location과 type 아예 분리되어 있어 둘 중 하나로만 서버에서 받아와도 필터링 한 번 더해야해서
아예 추가 api 요청 없이 필터링만 하도록 수정했습니다

제안서 필터링 추가

---

src/components/Common/Sidebar/TopBar.js
src/components/HomeCardDisplay/Card.js
src/pages/Proposal/Proposal.js

ui 수정 (상세 제안서, 카드 정사각형)

---

src/components/HomeCardDisplay/Card.js

fix : 카드 이미지 ui 수정

---

src/components/HomeCardDisplay/Card.js

fix : 카드 ui 수정

---

src/components/Common/SearchBar.js

feat:search bar 엔터 키 추가

---

src/components/AccountSetting/AccountRemovePop.js
src/pages/AccountSetting/AccountSetting.js

fix : member -> members
